version: '3.8'
services:
  torrent-downloader:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - NODE_ENV=production
    restart: unless-stopped